spring:
  profiles:
    default: local
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health-check

logging:
  config: classpath:logback.xml
