spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/matsosik_db
    username: root
    password: matsosik_password
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8082
